version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./writify_api" ]
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Add other environment variables as needed
    volumes:
      - .:/go/src/app
